#!/bin/sh

alias _ >/dev/null 2>&1 && unalias _
alias rm >/dev/null 2>&1 && unalias rm
alias cp >/dev/null 2>&1 && unalias cp
alias mv >/dev/null 2>&1 && unalias mv

# ls
alias ll='ls -lAh --group-directories-first'
alias l='ls -F --group-directories-first'
alias la='ls -A'
alias lsd='ls -d'

# vim
alias gvt='gvim --remote-tab'
vl() { vim -R -c 'set nomod nolist noma' -c 'map q :q<CR>' "${@:--}" ; }
vman() { man "$@" | vl -c 'set ft=man' - ; }
vinfo() { info "$@" | vl -c 'set ft=info' - ; }
[ -n "$BASH_VERSION" ] && complete -F _man vman
[ -n "$BASH_VERSION" ] && complete -F _info vinfo

# git
alias gst='git status'
alias gau='git add -u'
alias gaup='git add -u -p'
alias tiga='env TIG_DIFF_OPTS="-M -C --find-copies-harder" tig --all HEAD'
alias gitka='gitk --all'
[ -n "$BASH_VERSION" ] && complete -o default -o nospace -f _tig tiga
gd() { git diff -M -C --find-copies-harder "$@" | vl ; }
gdc() { git diff --cached -M -C --find-copies-harder "$@" | vl ; }

# misc
q() { "$@" >/dev/null 2>&1 ; }
alias gping='ping 8.8.8.8'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias ipysh='ipython --profile pysh --no-confirm-exit --no-banner'
alias api='sudo apt-get install'
vlgd() { godoc "$@" | vl ; }
vgd() { godoc "$@" | vl ; }
alias copy='xclip -selection clipboard'
alias blaze=bazel
lscat() { find "$@" -maxdepth 0 -type f -print -exec cat '{}' \; ; }

# go
gohere() {
  #GOPATH="${GOPATH+$GOPATH:}${PWD}" go "$@"
  #echo GOPATH="${PWD}${GOPATH+:$GOPATH}" go "$@"
  #GOPATH="${PWD}${GOPATH+:$GOPATH}" go "$@"
  #GOPATH="${GOPATH+$GOPATH:}${PWD}" go "$@"
  GOPATH="$PWD" go "$@"
}
