#!/bin/bash

alias _ >/dev/null 2>&1 && unalias _
alias rm >/dev/null 2>&1 && unalias rm
alias cp >/dev/null 2>&1 && unalias cp
alias mv >/dev/null 2>&1 && unalias mv

# ls
alias ll='ls -lAh --group-directories-first'
alias l='ls -F --group-directories-first'
alias la='ls -A'
alias lsd='ls -d'

# vim
export EDITOR=nvim
alias vim=nvim
alias gvt='gvim --remote-tab'
vl() { vim -R -c 'set nomod nolist noma' -c 'map q :q<CR>' "${@:--}" ; }
vman() { man "$@" | vl -c 'set ft=man' - ; }
vinfo() { info "$@" | vl -c 'set ft=info' - ; }
[ -n "$BASH_VERSION" ] && complete -F _man vman
[ -n "$BASH_VERSION" ] && complete -F _info vinfo
alias nv=nvim
alias nvconf='nvim ~/.config/nvim/init.vim'

# git
alias gst='git status'
alias gau='git add -u'
alias gaup='git add -u -p'
alias gco='git checkout'
alias gp='git pull --prune'
alias gf='git fetch --prune'
alias gps='git push'
alias tiga='env TIG_DIFF_OPTS="-M -C --find-copies-harder" tig --all HEAD'
tigl() {
  local branches
  local tags
  branches=($(git branch | sed 's/^[ *]*//'))
  tags=($(git tag))
  env TIG_DIFF_OPTS="-M -C --find-copies-harder" tig "${branches[@]}" "${tags[@]}" origin/master HEAD
}
alias gitka='gitk --all'
[ -n "$BASH_VERSION" ] && complete -o default -o nospace -f _tig tiga
gd() { git diff -M -C --find-copies-harder "$@" | vl ; }
gdc() { git diff --cached -M -C --find-copies-harder "$@" | vl ; }
gdm() { git diff -M -C --find-copies-harder "$(git merge-base HEAD origin/master)" "$@" | vl ; }

# go
gohere() { 
  local GOPATH="${PWD%/src/*}"
  local PATH="$PATH:${GOPATH//:/\/bin:}/bin"
  env GOPATH="$GOPATH" PATH="$PATH" go "$@"
}
gohererun() {
  local GOPATH="${PWD%/src/*}"
  local PATH="$PATH:${GOPATH//:/\/bin:}/bin"
  env GOPATH="$GOPATH" PATH="$PATH" "$@"
}

# misc
q() { "$@" >/dev/null 2>&1 ; }
alias gping='ping -OD 8.8.8.8'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias ipysh='ipython --profile pysh --no-confirm-exit --no-banner'
alias api='sudo apt-get install'
alias aps='aptitude search'
vlgd() { godoc "$@" | vl ; }
vgd() { godoc "$@" | vl ; }
alias copy='xclip -selection clipboard'
alias blaze=bazel
lscat() { find "$@" -maxdepth 0 -type f -print -exec cat '{}' \; ; }
psgrep() { ps -ef | grep "$@"; true ; }
onetail() {
  while read l; do
    echo -en "\033[2K"
    echo "$l" | cut -c-100 | tr -d '\n'
    echo -en '\r'
    #sleep 0.2
  done
}
alias ccat='pygmentize -f 16m -O bg=dark,style=trac'
alias rg='rg --hidden'
